# Use the official Python 3.11.9-alpine image as the base
FROM python:3.11.9-alpine

# Set the working directory within the container
WORKDIR /app

# Copy the Python script into the container
COPY pre-process-extended.py .

# Run the script using the CMD instruction
CMD ["python", "pre-process-extended.py"]
